---
apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-demo
  labels:
    kubernetes.io/metadata.name: rhdh-demo
  annotations:
    openshift.io/display-name: RHDH demo project
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhdh-demo-group
  namespace: rhdh-demo
spec:
  targetNamespaces:
    - rhdh-demo
...
