---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  K8S_SA_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IlhGNi1lSXlLZVluenJkel9rVTZ3VDV2TnNlNHVMdURRTzUtaF8wSmRkNVUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZW1vLXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmhkaC1rOHMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicmhkaC1rOHMtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJhNWVhMjY0MS01MDY0LTQ5YTAtODI4MS01ZWNkOGJhNTFhYjYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1wcm9qZWN0OnJoZGgtazhzLXNhIn0.QNdt7epjlx-0JW865PO5hiQJyOJpdCL0o_p7ufB1zd6YasGGn8VQ-yXeKjbSTj2X2DzzO1ZesNEcX40g_haSxl2k5oJqQdCvwfRFuuiDmLpFrkRrd7mIdb9q_EMq0Kvcjl4UXR3PpCzO8aJqdCWehGe_BrzDl4a81AlLdW2OLdHue7MnBuRelZkSVUatcvTM5DVQuZNNqpilZDbtXqHDKHS8uWjZh3WnRAinS-LjgjARGdyNXqmb1lApau_aMqqZRHzQ26xRmt2EwKd98KE_2kZE3TocYV0Xi__RifzU0hzbz3_qUL4Yen4nppl8pE-eu4c86MG06GZPCWyl6jVbWAsfklvmJ3uVXjRBoKtLO3hg38TZ4b7GlBovBFO3tt5RgHbkcWKfG0LGlnpVSSwnSZBc89Tmr_sXkRV7lR8fKUnjwY6v3_XVa5W1m58wjnmZ98T_OiXmcRj5axEY_IDILbsUAFoyRP2SWaDQiv07OzQXFRmG3Ug97q7YzOrCOIuRGuTnjoJv6AUOtRqhlyaan3bfuTaFWegCV_fhd2jD7rfPvXv0T-shFtt9IhgPGvEaxNd3GzTcuVRI9W5UABDNJX00GGPnex2xOsGt5irfsDzR3jg8YxoEESuu3hvk6-WL7OZxjIp0KshJ8yWILmvKlLn9ZUNCH5NnIdKbnPbZP8E
  GITHUB_TOKEN: <redacted>
