---
# Copy this to rhdh-secret.yaml which is not to be checked in
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  K8S_SA_TOKEN: "The token of the created ServiceAccount"
  GITHUB_TOKEN: "A classic token"
